In [ ]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:")
print(A)

B = np.random.randint(10, 20, size=(3, 3))

print("Matrix B:")
print(B)

A_T = A.T
print("Transpose of A:")
print(A_T)
A_T = A.transpose()
print("Transpose of A using transpose():")
print(A_T)

C = A + B
print("Sum of two matrices A and B:")
print(C)
D = A - B
print("Difference of two matrices A and B:")
print(D)



Matrix A:
[[1 1 4]
 [7 9 1]
 [3 3 6]]
Matrix B:
[[16 14 11]
 [14 11 18]
 [16 15 17]]
Transpose of A:
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Transpose of A using transpose():
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Sum of two matrices A and B:
[[17 15 15]
 [21 20 19]
 [19 18 23]]
Difference of two matrices A and B:
[[-15 -13  -7]
 [ -7  -2 -17]
 [-13 -12 -11]]


In [ ]:
#Note book 31/10/2025
#Dot product of two vectors
import numpy as np

v1 = np.random.randint(1, 10, size=5)
v2 = np.random.randint(10, 20, size=5)

print("Vector 1:")
print(v1)

print("vector 2:")
print(v2)

dot_product = np.dot(v1, v2)
print("Dot product of v1 and v2:")
print(dot_product)



Vector 1:
[8 3 7 8 2]
vector 2:
[10 12 14 19 15]
Dot product of v1 and v2:
396


In [14]:
#Notebook 31/10/2025
#Time: 8:23PM
#L2 Norm function

import math
import numpy as np

n = 10

v1 = np.random.randint(10, 100, size=(n))

print("Random vector with ", n, " dimensions: ")
print(v1)

L2_Norm = 0
for vi in v1:
    L2_Norm+=vi**2

L2_Norm = math.sqrt(L2_Norm)

print("L2_Norm of the given vector: ", L2_Norm)


Random vector with  10  dimensions: 
[21 36 52 63 90 99 51 77 73 10]
L2_Norm of the given vector:  200.67386476569388


In [ ]:
#Notebook 1/11/2025
#Time: 7:00AM
#Covariance Matrix

import numpy as np

def cov(A):
    N = A.shape[0]
    mean_vector = np.mean(A, axis=0) #axis = 0 calculate mean by column
    print("Mean value by column: ")
    print(mean_vector)
    B = A - mean_vector
    print("Mean subtract: ")
    print(B)

    #@ is dot product
    #B.T is B^T
    covariance_matrix_manual = (B.T @ B) / (N - 1)
    return covariance_matrix_manual

A = np.random.rand(10, 3)
#rowvar=False to calculate the covariance by column, default is by row
covariance_matrix_numpy = np.cov(A, rowvar=False)
covariance_matrix_manual = cov(A)

print("Covariance matrix by numpy: ")
print(covariance_matrix_numpy)
print("Covariance matrix by manual: ")
print(covariance_matrix_manual)


print("Two covariance matrix are equal: ", np.allclose(covariance_matrix_manual, covariance_matrix_numpy))

Mean value by column: 
[0.45878619 0.55184511 0.47315351]
Mean subtract: 
[[-0.08323064 -0.37525247  0.3248943 ]
 [ 0.00270225  0.08847487 -0.07144125]
 [ 0.16097438 -0.44235261  0.00439172]
 [ 0.05789707  0.17024737 -0.27377902]
 [ 0.0521797   0.20358782 -0.18253425]
 [-0.35601354  0.08426303  0.18179288]
 [-0.01557506 -0.0016001   0.01576902]
 [-0.3642262   0.25536129  0.03367282]
 [ 0.01798789  0.25416556  0.41806939]
 [ 0.52730414 -0.23689476 -0.45083561]]
Covariance matrix by numpy: 
[[ 0.06410493 -0.02917585 -0.03992678]
 [-0.02917585  0.0675313   0.0025554 ]
 [-0.03992678  0.0025554   0.07015768]]
Covariance matrix by manual: 
[[ 0.06410493 -0.02917585 -0.03992678]
 [-0.02917585  0.0675313   0.0025554 ]
 [-0.03992678  0.0025554   0.07015768]]
Two covariance matrix are equal:  True


In [15]:
#Notebook 2/11/2025
#Time: 6:43AM
#MSE (Mean Squared Error)
import numpy as np

def compute_cost(X, w, y):
    m = X.shape[0]
    #residual (The distance between model's predicted label and actual label)
    r = (X @ w - y)
    cost = np.sum(r**2) / m
    return cost

#m samples
#n features

m = 10
n = 2

X = np.random.rand(m, n)

#Add one more column for bias
X = np.concatenate((np.ones((m, 1)), X), axis=1)

print("Matrix X: ")
print(X)

#weights vector
w = np.random.rand(n+1, 1)

print("Model weights: ")
print(w)

#Actual label
y = np.random.rand(m, 1)
print("Actual label: ")
print(y)

print("MSE cost: ")
print(compute_cost(X, w, y))

Matrix X: 
[[1.         0.47227004 0.4688179 ]
 [1.         0.29705554 0.42838573]
 [1.         0.1601545  0.38057752]
 [1.         0.63719813 0.53314133]
 [1.         0.07300282 0.59002105]
 [1.         0.78884531 0.08999095]
 [1.         0.51918533 0.53889397]
 [1.         0.99319035 0.90051107]
 [1.         0.90360736 0.59886612]
 [1.         0.2015776  0.07285194]]
Model weights: 
[[0.61449247]
 [0.88900633]
 [0.77444083]]
Actual label: 
[[0.64411229]
 [0.1063106 ]
 [0.18017645]
 [0.94257188]
 [0.9767826 ]
 [0.59660312]
 [0.4559789 ]
 [0.97970861]
 [0.32872639]
 [0.4593046 ]]
MSE cost: 
0.8734553785148591


In [23]:
#Notebook 2/11/2025
#Time: 9:13AM
#Gradient Descent
import numpy as np

def compute_cost(X, w, y):
    m = X.shape[0]
    r = (X @ w - y)
    cost = np.sum(r**2) / m
    return cost

def gradient_descent(X, w, y, learning_rates, iterations):
    m = X.shape[0]
    cost_history = []

    #iterations: loop time
    for i in range(iterations):
        y_hat = X @ w

        #distances between predicted label and actual label
        errors = y_hat - y

        gradient = (2 / m) * (X.T @ errors)

        #decrease model weights by a small amount
        w = w - (learning_rates * gradient)

        if (i % 100 == 0):
            cost = compute_cost(X, w, y)
            cost_history.append(cost)

    return w, cost_history

m = 10 #samples
n = 2  #features
X = np.random.rand(m, n)
X = np.concatenate((np.ones((m, 1)), X), axis=1)
print("Matrix X: ")
print(X)

w = np.random.rand(n+1, 1)
y = np.random.rand(m, 1)

print("Model weights: ")
print(w)
print("Actual label: ")
print(y)

w, cost_history = gradient_descent(X, w, y, 0.01, 500)

print("Model final weight: ")
print(w)

print("Cost history: ")
print(cost_history)



Matrix X: 
[[1.         0.77269914 0.35255327]
 [1.         0.81435404 0.94732287]
 [1.         0.98538525 0.64664595]
 [1.         0.31027644 0.80382744]
 [1.         0.05576331 0.1429356 ]
 [1.         0.20950315 0.17667969]
 [1.         0.87010603 0.47781743]
 [1.         0.36854704 0.71607328]
 [1.         0.95177202 0.30553088]
 [1.         0.83165881 0.71991304]]
Model weights: 
[[0.64096711]
 [0.52602339]
 [0.71714328]]
Actual label: 
[[0.65356273]
 [0.85429434]
 [0.91637643]
 [0.16762086]
 [0.06776718]
 [0.96687263]
 [0.59462674]
 [0.63729414]
 [0.11812905]
 [0.24672686]]
Model final weight: 
[[0.24366123]
 [0.16799406]
 [0.31856472]]
Cost history: 
[np.float64(0.7794561590858946), np.float64(0.10840017399673647), np.float64(0.10655626754601619), np.float64(0.10559875980762737), np.float64(0.10483872378225219)]


In [105]:
#Notebook 3/11/2025
#Time: 6:51PM
#Calculate matrix rank

import numpy as np

m = 4
n = 4

A = np.random.randint(3, 100, size=(4, 4))
print("Matrix A: ")
print(A)
matrix_rank = np.linalg.matrix_rank(A)

print("Matrix rank of A: ")
print(matrix_rank)

Matrix A: 
[[23 32 14 24]
 [60 67  4 88]
 [32 57 46 24]
 [ 9 99 75 22]]
Matrix rank of A: 
4


In [211]:
#Notebook 3/11/2025
#Time: 10:16PM
#Linear independent

import numpy as np

def is_linear_independent(vectors):
    num_vec = len(vectors)
    matrix = np.stack(vectors, axis=1)
    print("Convert vectors to matrix: ")
    print(matrix)
    rank = np.linalg.matrix_rank(matrix)
    print("Rank of matrix: ", rank)
    if (rank==num_vec):
        return True
    return False

vectors = []
num_vec = 4

for i in range(num_vec):
    vec = np.random.randint(1, 100, size=(4))
    vectors.append(vec)

print("List of vectors: ")
print(vectors)

print("These vectors are linear independent: ", is_linear_independent(vectors))

List of vectors: 
[array([28, 36, 98, 49], dtype=int32), array([48, 51, 65, 89], dtype=int32), array([25, 55, 72, 85], dtype=int32), array([13, 27, 34, 38], dtype=int32)]
Convert vectors to matrix: 
[[28 48 25 13]
 [36 51 55 27]
 [98 65 72 34]
 [49 89 85 38]]
Rank of matrix:  4
These vectors are linear independent:  True


In [13]:
#Notebook 4/11/2025
#Time: 6:15PM
#column dimension of matrix

import numpy as np

def get_column_dimension(matrix):
    rank = np.linalg.matrix_rank(matrix)
    return rank

matrix = np.random.randint(1, 20, size=(5, 5))
print(matrix)
print("Dimension column of this matrix: ", get_column_dimension(matrix))

[[15  6  5  3 10]
 [19  9 11 16  9]
 [17  5  1  5 18]
 [ 5  9  7 17  3]
 [18 11  1 15  9]]
Dimension column of this matrix:  5


In [1]:
#Notebook 6/11/2025
#Time: 11:02AM
#Sigmoid function

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.rand(1, 10)

print("Sigmoid x: ", sigmoid(x))

Sigmoid x:  [[0.69167124 0.55147229 0.57186673 0.58664922 0.72532027 0.66940902
  0.71544457 0.71438673 0.65544246 0.61702122]]


In [19]:
#Notebook 7/11/2025
#Time: 6:52PM
#compute determinant

import numpy as np

def eliminate_ri_cj(A, i, j):
    B = []
    m = A.shape[0]
    n = A.shape[1]
    for row in range(0, m):
        new_row = []
        for col in range(0, n):
            if (row==i or col==j): continue
            new_row.append(A[row][col])
        if (len(new_row)!=0):
            B.append(new_row)

    new_matrix = np.array(B, dtype=np.int32)
    return new_matrix

def compute_determinant(A, by_row=0):
    #Matrix size m x n
    n = A.shape[1]

    if (n==2):
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]

    determinant = 0
    for i in range(0, n):
        if (A[by_row][i]==0): continue
        determinant+=(-1)**(by_row + i) * A[by_row][i]*compute_determinant(eliminate_ri_cj(A, by_row, i), by_row)
    return determinant


A = np.random.randint(1, 10, size=(4, 4))
print("Matrix A: ")
print(A)
print("Determinant of A: ")
print(compute_determinant(A, 0))

Matrix A: 
[[4 4 4 4]
 [5 1 4 7]
 [1 9 4 1]
 [7 9 4 4]]
Determinant of A: 
-192


In [9]:
#Notebook 8/11/2025
#Time: 12:32PM
#Compute deriative

def f(x):
    return x**2

def compute_deriative(x):
    h = 1e-6
    df_dx = (f(x+h) - f(x)) / h
    return df_dx


x = 2
print("Deriative of f(x)=x^2 at",x,"is:", compute_deriative(x))

Deriative of f(x)=x^2 at 2 is: 4.0000010006480125
