In [ ]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:")
print(A)

B = np.random.randint(10, 20, size=(3, 3))

print("Matrix B:")
print(B)

A_T = A.T
print("Transpose of A:")
print(A_T)
A_T = A.transpose()
print("Transpose of A using transpose():")
print(A_T)

C = A + B
print("Sum of two matrices A and B:")
print(C)
D = A - B
print("Difference of two matrices A and B:")
print(D)



Matrix A:
[[1 1 4]
 [7 9 1]
 [3 3 6]]
Matrix B:
[[16 14 11]
 [14 11 18]
 [16 15 17]]
Transpose of A:
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Transpose of A using transpose():
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Sum of two matrices A and B:
[[17 15 15]
 [21 20 19]
 [19 18 23]]
Difference of two matrices A and B:
[[-15 -13  -7]
 [ -7  -2 -17]
 [-13 -12 -11]]


In [ ]:
#Note book 31/10/2025
#Dot product of two vectors
import numpy as np

v1 = np.random.randint(1, 10, size=5)
v2 = np.random.randint(10, 20, size=5)

print("Vector 1:")
print(v1)

print("vector 2:")
print(v2)

dot_product = np.dot(v1, v2)
print("Dot product of v1 and v2:")
print(dot_product)



Vector 1:
[8 3 7 8 2]
vector 2:
[10 12 14 19 15]
Dot product of v1 and v2:
396


In [14]:
#Notebook 31/10/2025
#Time: 8:23PM
#L2 Norm function

import math
import numpy as np

n = 10

v1 = np.random.randint(10, 100, size=(n))

print("Random vector with ", n, " dimensions: ")
print(v1)

L2_Norm = 0
for vi in v1:
    L2_Norm+=vi**2

L2_Norm = math.sqrt(L2_Norm)

print("L2_Norm of the given vector: ", L2_Norm)


Random vector with  10  dimensions: 
[21 36 52 63 90 99 51 77 73 10]
L2_Norm of the given vector:  200.67386476569388


In [ ]:
#Notebook 1/11/2025
#Time: 7:00AM
#Covariance Matrix

import numpy as np

def cov(A):
    N = A.shape[0]
    mean_vector = np.mean(A, axis=0) #axis = 0 calculate mean by column
    print("Mean value by column: ")
    print(mean_vector)
    B = A - mean_vector
    print("Mean subtract: ")
    print(B)

    #@ is dot product
    #B.T is B^T
    covariance_matrix_manual = (B.T @ B) / (N - 1)
    return covariance_matrix_manual

A = np.random.rand(10, 3)
#rowvar=False to calculate the covariance by column, default is by row
covariance_matrix_numpy = np.cov(A, rowvar=False)
covariance_matrix_manual = cov(A)

print("Covariance matrix by numpy: ")
print(covariance_matrix_numpy)
print("Covariance matrix by manual: ")
print(covariance_matrix_manual)


print("Two covariance matrix are equal: ", np.allclose(covariance_matrix_manual, covariance_matrix_numpy))

Mean value by column: 
[0.45878619 0.55184511 0.47315351]
Mean subtract: 
[[-0.08323064 -0.37525247  0.3248943 ]
 [ 0.00270225  0.08847487 -0.07144125]
 [ 0.16097438 -0.44235261  0.00439172]
 [ 0.05789707  0.17024737 -0.27377902]
 [ 0.0521797   0.20358782 -0.18253425]
 [-0.35601354  0.08426303  0.18179288]
 [-0.01557506 -0.0016001   0.01576902]
 [-0.3642262   0.25536129  0.03367282]
 [ 0.01798789  0.25416556  0.41806939]
 [ 0.52730414 -0.23689476 -0.45083561]]
Covariance matrix by numpy: 
[[ 0.06410493 -0.02917585 -0.03992678]
 [-0.02917585  0.0675313   0.0025554 ]
 [-0.03992678  0.0025554   0.07015768]]
Covariance matrix by manual: 
[[ 0.06410493 -0.02917585 -0.03992678]
 [-0.02917585  0.0675313   0.0025554 ]
 [-0.03992678  0.0025554   0.07015768]]
Two covariance matrix are equal:  True


In [15]:
#Notebook 2/11/2025
#Time: 6:43AM
#MSE (Mean Squared Error)
import numpy as np

def compute_cost(X, w, y):
    m = X.shape[0]
    #residual (The distance between model's predicted label and actual label)
    r = (X @ w - y)
    cost = np.sum(r**2) / m
    return cost

#m samples
#n features

m = 10
n = 2

X = np.random.rand(m, n)

#Add one more column for bias
X = np.concatenate((np.ones((m, 1)), X), axis=1)

print("Matrix X: ")
print(X)

#weights vector
w = np.random.rand(n+1, 1)

print("Model weights: ")
print(w)

#Actual label
y = np.random.rand(m, 1)
print("Actual label: ")
print(y)

print("MSE cost: ")
print(compute_cost(X, w, y))

Matrix X: 
[[1.         0.47227004 0.4688179 ]
 [1.         0.29705554 0.42838573]
 [1.         0.1601545  0.38057752]
 [1.         0.63719813 0.53314133]
 [1.         0.07300282 0.59002105]
 [1.         0.78884531 0.08999095]
 [1.         0.51918533 0.53889397]
 [1.         0.99319035 0.90051107]
 [1.         0.90360736 0.59886612]
 [1.         0.2015776  0.07285194]]
Model weights: 
[[0.61449247]
 [0.88900633]
 [0.77444083]]
Actual label: 
[[0.64411229]
 [0.1063106 ]
 [0.18017645]
 [0.94257188]
 [0.9767826 ]
 [0.59660312]
 [0.4559789 ]
 [0.97970861]
 [0.32872639]
 [0.4593046 ]]
MSE cost: 
0.8734553785148591
