In [ ]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:")
print(A)

B = np.random.randint(10, 20, size=(3, 3))

print("Matrix B:")
print(B)

A_T = A.T
print("Transpose of A:")
print(A_T)
A_T = A.transpose()
print("Transpose of A using transpose():")
print(A_T)

C = A + B
print("Sum of two matrices A and B:")
print(C)
D = A - B
print("Difference of two matrices A and B:")
print(D)



Matrix A:
[[1 1 4]
 [7 9 1]
 [3 3 6]]
Matrix B:
[[16 14 11]
 [14 11 18]
 [16 15 17]]
Transpose of A:
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Transpose of A using transpose():
[[1 7 3]
 [1 9 3]
 [4 1 6]]
Sum of two matrices A and B:
[[17 15 15]
 [21 20 19]
 [19 18 23]]
Difference of two matrices A and B:
[[-15 -13  -7]
 [ -7  -2 -17]
 [-13 -12 -11]]


In [ ]:
#Note book 31/10/2025
#Dot product of two vectors
import numpy as np

v1 = np.random.randint(1, 10, size=5)
v2 = np.random.randint(10, 20, size=5)

print("Vector 1:")
print(v1)

print("vector 2:")
print(v2)

dot_product = np.dot(v1, v2)
print("Dot product of v1 and v2:")
print(dot_product)



Vector 1:
[8 3 7 8 2]
vector 2:
[10 12 14 19 15]
Dot product of v1 and v2:
396


In [14]:
#Notebook 31/10/2025
#Time: 8:23PM
#L2 Norm function

import math
import numpy as np

n = 10

v1 = np.random.randint(10, 100, size=(n))

print("Random vector with ", n, " dimensions: ")
print(v1)

L2_Norm = 0
for vi in v1:
    L2_Norm+=vi**2

L2_Norm = math.sqrt(L2_Norm)

print("L2_Norm of the given vector: ", L2_Norm)


Random vector with  10  dimensions: 
[21 36 52 63 90 99 51 77 73 10]
L2_Norm of the given vector:  200.67386476569388


In [ ]:
#Notebook 1/11/2025
#Time: 7:00AM
#Convariance Matrix

import numpy as np

def cov(A):
    N = A.shape[0]
    mean_vector = np.mean(A, axis=0) #axis = 0 calculate mean by column
    print(mean_vector)
    return A

A = np.random.rand(10, 3)
cov(A)

[0.56572356 0.44857095 0.33118899]


array([[6.76420926e-01, 9.72950170e-01, 4.64413043e-01],
       [9.53539164e-01, 4.38829887e-01, 1.94343726e-01],
       [5.26697437e-01, 4.80914621e-04, 2.68399034e-01],
       [1.61168491e-01, 4.98881866e-01, 2.76787712e-01],
       [1.06934867e-02, 8.95998664e-01, 3.44669405e-01],
       [9.22796320e-01, 4.78237885e-02, 1.40235008e-01],
       [3.78650527e-01, 4.26259338e-01, 7.68989758e-02],
       [2.80210216e-01, 1.85786552e-01, 6.36876197e-01],
       [7.68476418e-01, 2.32383591e-01, 4.92553808e-01],
       [9.78582664e-01, 7.86314770e-01, 4.16712985e-01]])